### ISSUE TITLE
Can you also please add react-native-cli

### ISSUE THREAD

**Issue by ans-4175** [sumartoyo/docker-android-nodejs#2]
I think react-native-cli should included in this image
`RUN npm install -g react-native-cli`

How do you think?

**Comment by sumartoyo** [comment]
The purpose of this box is to provide general purpose android and nodejs enviroment, hence the name is `docker-android-nodejs` and not `docker-react-native`. If we provide React Native I'm afraid people will also request us to provide Vue, Angular, etc. Moreover, installing npm dependencies in the Dockerfile will only insall old version of the dependencies e.g. the version when the box is built.
